name: pokedex-nest-mongo

services:
  db:
    container_name: mongo
    image: mongo:5
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_DATABASE: nest-pokedex
    volumes:
      - ./mongo:/data/db
